import Link from "next/link";
import { ArrowRight, BarChart3, Building2, CheckCircle2, Database, FileCheck2, ShieldCheck, Sparkles, TrendingUp, Users, WalletCards } from "lucide-react";
import { MarketingPage } from "@/components/MarketingPage";

const solutions = [
  [Database, "01", "Structurer", "Un référentiel clair pour rassembler les informations essentielles de votre entreprise."],
  [FileCheck2, "02", "Documenter", "Associez chaque information importante à une preuve, une source ou un justificatif."],
  [ShieldCheck, "03", "Contrôler", "Détectez incohérences, données manquantes et points nécessitant une vérification."],
  [BarChart3, "04", "Mesurer", "Transformez les données contrôlées en indicateurs lisibles et en Score Pass."],
] as const;

const stats = [["+500", "entreprises accompagnées"], ["+1,2 M", "sources de données"], ["+12 000", "preuves vérifiées"], ["+3 500", "évaluations réalisées"]];

export default function Home() {
  return <MarketingPage>
    <main>
      <section className="pro-hero">
        <div className="pro-hero-photo"/><div className="pro-hero-grid"/><div className="pro-hero-orb orb-a"/><div className="pro-hero-orb orb-b"/>
        <div className="pro-container pro-hero-inner">
          <div className="pro-hero-copy"><span className="pro-kicker light"><Sparkles size={14}/> PLATEFORME DE CRÉDIBILITÉ ÉCONOMIQUE</span><h1>La confiance<br/><em>devient un actif.</em></h1><p>TOLBO transforme les données d’entreprise en informations structurées, preuves traçables et indicateurs de crédibilité pour une prise de décision plus éclairée.</p><div className="pro-actions"><Link href="/register" className="pro-orange-btn large">Évaluer mon entreprise <ArrowRight size={17}/></Link><Link href="/score-pass" className="pro-glass-btn large">Découvrir le Score Pass</Link></div><div className="pro-trust"><span><CheckCircle2 size={15}/> Données structurées</span><span><CheckCircle2 size={15}/> Preuves traçables</span><span><CheckCircle2 size={15}/> Versionnement</span></div></div>
          <div className="pro-hero-dashboard"><div className="dashboard-glow"/><div className="dashboard-card"><div className="dash-top"><span>TOLBO / SCORE PASS</span><i>● Évaluation active</i></div><div className="dash-main"><div className="dash-score"><span>CRÉDIBILITÉ ÉCONOMIQUE</span><div className="dash-ring"><strong>78</strong><small>/100</small></div><b><ShieldCheck size={14}/> Dossier suffisamment documenté</b></div><div className="dash-data"><div className="dash-kpis"><span><b>37</b>Données</span><span><b>79</b>Indice</span><span><b>24</b>Contrôles</span></div><div className="dash-chart"><div className="chart-line"/><i/><i/><i/><i/><i/><i/></div><div className="dash-bars"><span>Identité <b style={{width:"92%"}}/></span><span>Activité <b style={{width:"78%"}}/></span><span>Finance <b style={{width:"71%"}}/></span><span>Gouvernance <b style={{width:"84%"}}/></span></div></div></div><div className="dash-bottom"><span><CheckCircle2 size={13}/> 31 preuves vérifiées</span><span><ShieldCheck size={13}/> Traçabilité active</span><span><TrendingUp size={13}/> +18 points</span></div></div><div className="floating-proof"><ShieldCheck size={18}/><span><b>Preuve vérifiée</b><small>Document associé · 98%</small></span></div><div className="floating-score"><TrendingUp size={18}/><span><b>+18 points</b><small>depuis la dernière revue</small></span></div></div>
        </div>
      </section>

      <section className="pro-stats"><div className="pro-container pro-stats-grid">{stats.map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div></section>

      <section className="pro-section" id="solutions"><div className="pro-container"><div className="pro-section-head"><div><span className="pro-kicker">NOS SOLUTIONS</span><h2>De la donnée brute<br/>à la confiance mesurable.</h2></div><p>TOLBO accompagne chaque étape de la chaîne de valeur de la donnée : collecte, structuration, contrôle et analyse.</p></div><div className="pro-solution-grid">{solutions.map(([Icon,n,title,text])=><Link href="/solutions" className="pro-solution" key={n}><div className="pro-solution-icon"><Icon size={23}/></div><small>{n}</small><h3>{title}</h3><p>{text}</p><span className="pro-arrow"><ArrowRight size={17}/></span></Link>)}</div></div></section>

      <section className="pro-editorial"><div className="pro-editorial-photo"><div className="pro-photo-overlay"/><div className="pro-photo-caption"><span>ARCHITECTURE DE LA DONNÉE</span><strong>Une lecture à 360°<br/>de votre entreprise.</strong></div></div><div className="pro-editorial-copy"><span className="pro-kicker">POURQUOI TOLBO ?</span><h2>Les données n'ont de valeur que lorsqu'elles peuvent être comprises et vérifiées.</h2><p>Nous croisons les données fiables et les justificatifs pour offrir une lecture structurée de l’identité, de l’activité, de la finance, de la gouvernance et des perspectives.</p><div className="pro-feature-list"><span><Building2/> Identité & existence</span><span><WalletCards/> Activité & modèle</span><span><ShieldCheck/> Finance & gouvernance</span><span><FileCheck2/> Preuves & conformité</span></div><Link href="/methode" className="pro-text-link">Découvrir notre méthode <ArrowRight size={16}/></Link></div></section>

      <section className="pro-score-section" id="score-pass"><div className="pro-container"><div className="pro-score-intro"><div><span className="pro-kicker light">SCORE PASS</span><h2>Un score qui rend la crédibilité lisible.</h2><p>Une synthèse visuelle pour comprendre rapidement la qualité, la complétude et la traçabilité d’un dossier.</p><Link href="/score-pass" className="pro-glass-btn">Explorer Score Pass <ArrowRight size={16}/></Link></div><div className="pro-big-score"><div className="big-ring"><strong>78</strong><small>/100</small></div><span>CRÉDIBILITÉ<br/>ÉCONOMIQUE</span></div></div><div className="pro-dimensions">{[["Identité & existence",92],["Activité & modèle",78],["Situation financière",71],["Gouvernance",84],["Traçabilité",66]].map(([l,v])=><div key={l}><span>{l}<b>{v}</b></span><i><em style={{width:`${v}%`}}/></i></div>)}</div></div></section>

      <section className="pro-section pro-method" id="methode"><div className="pro-container"><div className="pro-section-head"><div><span className="pro-kicker">COMMENT ÇA MARCHE ?</span><h2>Un parcours simple,<br/>clair et sécurisé.</h2></div><p>De la création de votre espace à la restitution, chaque étape est conçue pour garder une information lisible et traçable.</p></div><div className="pro-steps">{[["01","Créer","votre espace"],["02","Déclarer","vos données"],["03","Déposer","vos preuves"],["04","Contrôler","& compléter"],["05","Obtenir","votre Score Pass"]].map(([n,t,s],i)=><div className={i===4?"active":""} key={n}><span>{n}</span><b>{t}</b><small>{s}</small>{i<4&&<ArrowRight size={16}/>}</div>)}</div></div></section>

      <section className="pro-business" id="entreprises"><div className="pro-container pro-business-grid"><div className="pro-business-photo"/><div><span className="pro-kicker">POUR LES ENTREPRISES</span><h2>Valorisez votre crédibilité et gagnez en confiance.</h2><p>Préparez un dossier plus clair, prouvez votre sérieux et facilitez les échanges avec vos partenaires.</p><div className="pro-benefits"><span><Users/> Accès à des partenaires de confiance</span><span><TrendingUp/> Meilleure visibilité de votre activité</span><span><FileCheck2/> Simplification des démarches</span></div><Link href="/entreprises" className="pro-navy-btn">Découvrir l’espace entreprise <ArrowRight size={16}/></Link></div></div></section>

      <section className="pro-insights" id="insights"><div className="pro-container"><div className="pro-section-head"><div><span className="pro-kicker">INSIGHTS</span><h2>La donnée devient<br/>une information utile.</h2></div><Link href="/actualites" className="pro-text-link">Voir tous les insights <ArrowRight size={16}/></Link></div><div className="pro-insight-grid"><Link href="/actualites" className="pro-insight insight-one"><div><small>DATA & PME</small><h3>La donnée, un levier pour la croissance des entreprises.</h3><span>Lire l’article <ArrowRight size={14}/></span></div></Link><Link href="/actualites" className="pro-insight insight-two"><div><small>TECHNOLOGIE</small><h3>L’IA au service de la fiabilité des données.</h3><span>Lire l’article <ArrowRight size={14}/></span></div></Link><Link href="/actualites" className="pro-insight insight-three"><div><small>TOLBO</small><h3>Un nouveau partenaire pour la crédibilité économique.</h3><span>Lire l’article <ArrowRight size={14}/></span></div></Link></div></div></section>
    </main>
  </MarketingPage>;
}
