"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Building2, CheckCircle2, Mail, ShieldCheck, UserRound, LockKeyhole } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { TolboLogo } from "@/components/TolboLogo";
import { AuthVisual } from "@/components/AuthVisual";

export default function Register(){
 const [name,setName]=useState("");const [company,setCompany]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");const router=useRouter();
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");const {data,error}=await createClient().auth.signUp({email:email.trim(),password,options:{data:{full_name:name.trim(),company_name:company.trim()}}});if(error){setError("Impossible de créer le compte. Vérifiez les informations saisies puis réessayez.");setBusy(false);return;}router.push(data.session?"/onboarding":"/check-email");}
 return <main className="auth-page"><AuthVisual mode="register"/><section className="auth-form-side"><div className="auth-topbar"><TolboLogo compact/><span className="auth-security"><ShieldCheck size={14}/> Création sécurisée</span></div><div className="auth-form-wrap"><span className="auth-breadcrumb"><Building2 size={12}/> CRÉER UN ESPACE</span><h2>Construisez votre crédibilité avec TOLBO.</h2><p>Créez votre espace entreprise pour centraliser vos informations, vos preuves et votre parcours Score Pass.</p><div className="auth-form-card"><form onSubmit={submit}><div className="auth-field"><label htmlFor="name">NOM COMPLET</label><div style={{position:"relative"}}><UserRound size={16} style={{position:"absolute",left:13,top:15,color:"#8ca0b2"}}/><input id="name" required value={name} onChange={e=>setName(e.target.value)} placeholder="Votre nom complet" style={{paddingLeft:40}}/></div></div><div className="auth-field"><label htmlFor="company">ENTREPRISE</label><div style={{position:"relative"}}><Building2 size={16} style={{position:"absolute",left:13,top:15,color:"#8ca0b2"}}/><input id="company" required value={company} onChange={e=>setCompany(e.target.value)} placeholder="Nom de votre entreprise" style={{paddingLeft:40}}/></div></div><div className="auth-field"><label htmlFor="email">E-MAIL PROFESSIONNEL</label><div style={{position:"relative"}}><Mail size={16} style={{position:"absolute",left:13,top:15,color:"#8ca0b2"}}/><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="nom@entreprise.com" style={{paddingLeft:40}}/></div></div><div className="auth-field"><label htmlFor="password">MOT DE PASSE</label><div style={{position:"relative"}}><LockKeyhole size={16} style={{position:"absolute",left:13,top:15,color:"#8ca0b2"}}/><input id="password" type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="8 caractères minimum" style={{paddingLeft:40}}/></div></div>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?"Création en cours…":"Créer mon espace"}</button></form><div className="auth-security"><CheckCircle2 size={13}/> Parcours guidé · Données structurées · Score Pass</div><p className="auth-foot-note">Vous avez déjà un compte ? <Link href="/login">Se connecter</Link></p></div></div></section></main>;
}
