create extension if not exists "pgcrypto";

do $$ begin create type public.organization_role as enum ('CLIENT_ADMIN','CLIENT_USER','TOLBO_ADMIN','TOLBO_ANALYST','TOLBO_CONTROLLER','TOLBO_VIEWER'); exception when duplicate_object then null; end $$;

do $$ begin create type public.dossier_status as enum ('EVALUABLE','NOT_APPLICABLE','NOT_EVALUABLE_MISSING','NOT_EVALUABLE_EVIDENCE','COLD_START','TEMP_UNAVAILABLE','REFUSED','UNDER_VERIFICATION','IN_PROGRESS','VERIFICATION','SUSPENDED','PROFILE_BUILDING','WITH_RESERVATION','INCOMPLETE','SCORE_PRODUCED','INTERRUPTED'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text,avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null,logo_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.organization_members(organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role public.organization_role not null default 'CLIENT_USER',created_at timestamptz not null default now(),primary key(organization_id,user_id));
create table if not exists public.enterprises(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,legal_name text not null,registration_number text,sector text,country text,address text,website text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.model_versions(id uuid primary key default gen_random_uuid(),version text unique not null,status text not null,description text,approved_at timestamptz,effective_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.evaluations(id uuid primary key default gen_random_uuid(),enterprise_id uuid not null references public.enterprises(id) on delete cascade,model_version text not null default 'V1.0',evaluation_date date,observation_period text,dossier_status public.dossier_status not null default 'IN_PROGRESS',score_pass numeric(5,2),score_internal numeric(7,4),iqp numeric(7,4),coverage numeric(7,4),freshness_status text,limitations text[],mandatory_notice text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.evaluation_variables(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.evaluations(id) on delete cascade,variable_id text not null,value_text text,value_numeric numeric,value_date date,status text not null default 'IN_PROGRESS',source text,updated_at timestamptz not null default now(),unique(evaluation_id,variable_id));
create table if not exists public.evaluation_dimensions(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.evaluations(id) on delete cascade,dimension_code text not null,score numeric(7,4),status text,coverage numeric(7,4),unique(evaluation_id,dimension_code));
create table if not exists public.evidence(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.evaluations(id) on delete cascade,variable_id text,level text,description text,document_id uuid,verified_by uuid references auth.users(id),verified_at timestamptz);
create table if not exists public.documents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,evaluation_id uuid references public.evaluations(id) on delete cascade,file_name text not null,storage_path text not null,mime_type text,file_size bigint,document_type text,status text not null default 'RECEIVED',uploaded_by uuid references auth.users(id),created_at timestamptz not null default now());
create table if not exists public.requests(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,evaluation_id uuid references public.evaluations(id) on delete cascade,title text not null,description text,status text not null default 'OPEN',priority text default 'NORMAL',due_date date,created_by uuid references auth.users(id),created_at timestamptz not null default now(),closed_at timestamptz);
create table if not exists public.anomalies(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,evaluation_id uuid references public.evaluations(id) on delete cascade,code text not null,level text not null,description text not null,status text not null default 'OPEN',impact text,decision text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),closed_at timestamptz);
create table if not exists public.hard_gates(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references public.evaluations(id) on delete cascade,code text not null,triggered boolean not null default false,reason text,decided_by uuid references auth.users(id),decided_at timestamptz,unique(evaluation_id,code));
create table if not exists public.scores(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null unique references public.evaluations(id) on delete cascade,model_version text not null,score_pass numeric(5,2),score_internal numeric(7,4),iqp numeric(7,4),dimension_scores jsonb,hard_gates jsonb,limitations jsonb,calculated_at timestamptz not null default now());
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid references auth.users(id),title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.audit_events(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,actor_id uuid references auth.users(id),event_type text not null,entity_type text,entity_id uuid,metadata jsonb,created_at timestamptz not null default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name) values(new.id,new.raw_user_meta_data->>'full_name') on conflict(id) do update set full_name=excluded.full_name,updated_at=now(); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_org_member(target_org uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from public.organization_members m where m.organization_id=target_org and m.user_id=auth.uid()); $$;
create or replace function public.is_client_admin(target_org uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from public.organization_members m where m.organization_id=target_org and m.user_id=auth.uid() and m.role='CLIENT_ADMIN'); $$;
create or replace function public.is_tolbo_staff() returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from public.organization_members m where m.user_id=auth.uid() and m.role in('TOLBO_ADMIN','TOLBO_ANALYST','TOLBO_CONTROLLER','TOLBO_VIEWER')); $$;

alter table public.profiles enable row level security; alter table public.organizations enable row level security; alter table public.organization_members enable row level security; alter table public.enterprises enable row level security; alter table public.model_versions enable row level security; alter table public.evaluations enable row level security; alter table public.evaluation_variables enable row level security; alter table public.evaluation_dimensions enable row level security; alter table public.evidence enable row level security; alter table public.documents enable row level security; alter table public.requests enable row level security; alter table public.anomalies enable row level security; alter table public.hard_gates enable row level security; alter table public.scores enable row level security; alter table public.notifications enable row level security; alter table public.audit_events enable row level security;

drop policy if exists profile_self on public.profiles; create policy profile_self on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists org_read on public.organizations; create policy org_read on public.organizations for select using(public.is_org_member(id) or public.is_tolbo_staff());
drop policy if exists org_insert on public.organizations; create policy org_insert on public.organizations for insert to authenticated with check(true);
drop policy if exists org_update on public.organizations; create policy org_update on public.organizations for update using(public.is_client_admin(id) or public.is_tolbo_staff()) with check(public.is_client_admin(id) or public.is_tolbo_staff());
drop policy if exists member_read on public.organization_members; create policy member_read on public.organization_members for select using(user_id=auth.uid() or public.is_org_member(organization_id) or public.is_tolbo_staff());
drop policy if exists member_insert on public.organization_members; create policy member_insert on public.organization_members for insert to authenticated with check(user_id=auth.uid() or public.is_tolbo_staff());
drop policy if exists member_update on public.organization_members; create policy member_update on public.organization_members for update using(public.is_client_admin(organization_id) or public.is_tolbo_staff());
drop policy if exists member_delete on public.organization_members; create policy member_delete on public.organization_members for delete using(public.is_client_admin(organization_id) or public.is_tolbo_staff());
drop policy if exists enterprise_all on public.enterprises; create policy enterprise_all on public.enterprises for all using(public.is_org_member(organization_id) or public.is_tolbo_staff()) with check(public.is_org_member(organization_id) or public.is_tolbo_staff());
drop policy if exists eval_all on public.evaluations; create policy eval_all on public.evaluations for all using(public.is_tolbo_staff() or exists(select 1 from public.enterprises e where e.id=enterprise_id and public.is_org_member(e.organization_id))) with check(public.is_tolbo_staff() or exists(select 1 from public.enterprises e where e.id=enterprise_id and public.is_org_member(e.organization_id)));
drop policy if exists evvar_all on public.evaluation_variables; create policy evvar_all on public.evaluation_variables for all using(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id))) with check(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id)));
drop policy if exists evdim_all on public.evaluation_dimensions; create policy evdim_all on public.evaluation_dimensions for all using(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id))) with check(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id)));
drop policy if exists evidence_all on public.evidence; create policy evidence_all on public.evidence for all using(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id))) with check(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id)));
drop policy if exists doc_all on public.documents; create policy doc_all on public.documents for all using(public.is_org_member(organization_id) or public.is_tolbo_staff()) with check(public.is_org_member(organization_id) or public.is_tolbo_staff());
drop policy if exists req_all on public.requests; create policy req_all on public.requests for all using(public.is_org_member(organization_id) or public.is_tolbo_staff()) with check(public.is_org_member(organization_id) or public.is_tolbo_staff());
drop policy if exists anomaly_all on public.anomalies; create policy anomaly_all on public.anomalies for all using(public.is_org_member(organization_id) or public.is_tolbo_staff()) with check(public.is_tolbo_staff() or public.is_org_member(organization_id));
drop policy if exists gate_all on public.hard_gates; create policy gate_all on public.hard_gates for all using(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id))) with check(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id)));
drop policy if exists score_read on public.scores; create policy score_read on public.scores for select using(public.is_tolbo_staff() or exists(select 1 from public.evaluations ev join public.enterprises e on e.id=ev.enterprise_id where ev.id=evaluation_id and public.is_org_member(e.organization_id)));
drop policy if exists score_staff_write on public.scores; create policy score_staff_write on public.scores for all using(public.is_tolbo_staff()) with check(public.is_tolbo_staff());
drop policy if exists notif_all on public.notifications; create policy notif_all on public.notifications for all using(user_id=auth.uid() or public.is_tolbo_staff());
drop policy if exists audit_read on public.audit_events; create policy audit_read on public.audit_events for select using(public.is_tolbo_staff() or public.is_org_member(organization_id));
drop policy if exists audit_insert on public.audit_events; create policy audit_insert on public.audit_events for insert to authenticated with check(actor_id=auth.uid());

insert into public.model_versions(version,status,description) values('V1.0','PRE_PILOT','Première version opérationnelle du paramétrage Score Pass V1') on conflict(version) do nothing;
insert into storage.buckets(id,name,public) values('organization-logos','organization-logos',true) on conflict(id) do nothing;
insert into storage.buckets(id,name,public) values('documents','documents',false) on conflict(id) do nothing;
drop policy if exists logos_read on storage.objects; create policy logos_read on storage.objects for select using(bucket_id='organization-logos');
drop policy if exists logos_insert on storage.objects; create policy logos_insert on storage.objects for insert to authenticated with check(bucket_id='organization-logos' and public.is_org_member((storage.foldername(name))[1]::uuid));
drop policy if exists logos_update on storage.objects; create policy logos_update on storage.objects for update to authenticated using(bucket_id='organization-logos' and public.is_org_member((storage.foldername(name))[1]::uuid)) with check(bucket_id='organization-logos' and public.is_org_member((storage.foldername(name))[1]::uuid));
drop policy if exists docs_read on storage.objects; create policy docs_read on storage.objects for select to authenticated using(bucket_id='documents' and (public.is_org_member((storage.foldername(name))[1]::uuid) or public.is_tolbo_staff()));
drop policy if exists docs_insert on storage.objects; create policy docs_insert on storage.objects for insert to authenticated with check(bucket_id='documents' and (public.is_org_member((storage.foldername(name))[1]::uuid) or public.is_tolbo_staff()));
drop policy if exists docs_delete on storage.objects; create policy docs_delete on storage.objects for delete to authenticated using(bucket_id='documents' and (public.is_org_member((storage.foldername(name))[1]::uuid) or public.is_tolbo_staff()));
